/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353534",
        "secondary-fixed": "#e2e2e2",
        "on-primary": "#67001b",
        "inverse-primary": "#bc0b3b",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-bright": "#393939",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#64dca0",
        "on-tertiary-fixed-variant": "#005233",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#ffdadb",
        "surface-tint": "#ffb2b7",
        "secondary-fixed-dim": "#c6c6c7",
        "on-primary-fixed-variant": "#92002a",
        "on-error": "#690005",
        "primary-container": "#ff516a",
        "on-tertiary": "#003822",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-container": "#b4b5b5",
        "on-secondary-fixed-variant": "#454747",
        "on-tertiary-container": "#00311d",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed": "#002112",
        "inverse-on-surface": "#313030",
        "error": "#ffb4ab",
        "outline": "#aa888a",
        "on-primary-fixed": "#40000d",
        "on-secondary-fixed": "#1a1c1c",
        "background": "#0b0b0b",
        "on-secondary": "#2f3131",
        "tertiary-container": "#1fa46d",
        "secondary": "#c6c6c7",
        "primary-fixed-dim": "#ffb2b7",
        "tertiary": "#64dca0",
        "error-container": "#93000a",
        "secondary-container": "#454747",
        "surface-container-highest": "#353534",
        "on-surface-variant": "#e3bdbf",
        "on-background": "#e5e2e1",
        "outline-variant": "#5b4041",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "tertiary-fixed": "#82f9ba",
        "primary": "#ffb2b7",
        "surface": "#131313",
        "on-primary-container": "#5b0017",
        "status-emergency": "#EF4444",
        "status-occupied": "#6366F1",
        "status-available": "#10B981",
        "status-maintenance": "#F59E0B"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "max-width": "1440px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "base": "8px"
      },
      fontFamily: {
        "headline-sm": ["Libre Caslon Text", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Libre Caslon Text", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "display-lg-mobile": ["36px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      },
      keyframes: {
        slideInRight: {
          '0%':   { opacity: '0', transform: 'translateX(100%)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        slideInRight: 'slideInRight 0.2s ease-out',
      },
    },
  },
  plugins: [],
}

