-- ============================================================
-- BlockFlow — Security Dashboard Tables
-- Migration: 008_security.sql
-- ============================================================

-- Gate passes generated by residents for visitors
create table public.gate_passes (
  id           uuid primary key default gen_random_uuid(),
  resident_id  uuid references public.users(id) on delete cascade,
  society_id   uuid references public.societies(id) on delete cascade,
  visitor_name text not null,
  visitor_phone text,
  purpose      text,
  otp          text not null,
  status       text check (status in ('pending', 'approved', 'denied', 'expired')) default 'pending',
  valid_until  timestamptz not null,
  created_at   timestamptz default now()
);

-- Visitor log (both pre-approved and walk-in)
create table public.visitor_log (
  id            uuid primary key default gen_random_uuid(),
  society_id    uuid references public.societies(id) on delete cascade,
  visitor_name  text not null,
  visiting_flat text,
  resident_id   uuid references public.users(id) on delete set null,
  gate_pass_id  uuid references public.gate_passes(id) on delete set null,
  entry_type    text check (entry_type in ('pre_approved', 'walk_in')) default 'walk_in',
  logged_by     uuid references public.users(id) on delete set null,
  purpose       text,
  status        text check (status in ('inside', 'exited')) default 'inside',
  entry_time    timestamptz default now(),
  exit_time     timestamptz
);

-- Staff log (housekeeping, technicians, etc.)
create table public.staff_log (
  id            uuid primary key default gen_random_uuid(),
  society_id    uuid references public.societies(id) on delete cascade,
  staff_name    text not null,
  staff_type    text check (staff_type in ('housekeeping', 'technician', 'security', 'other')) default 'other',
  visiting_flat text,
  logged_by     uuid references public.users(id) on delete set null,
  status        text check (status in ('inside', 'exited')) default 'inside',
  entry_time    timestamptz default now(),
  exit_time     timestamptz
);

alter table public.gate_passes  disable row level security;
alter table public.visitor_log  disable row level security;
alter table public.staff_log    disable row level security;
